const carlist = [
  {
    id: 1,
    make: "Peugeot",
    model: "e-208",
    image: "./assets/carimages/Peugeot.png",
    useablecapkWH: 50.0,
    rangemiles: 185,
    acceleration: 8.1,
    topspeedmph: 93,
    torque: 192,
    body: "Hatchback",
    fastchargemins: 28,
    standardcharge: 465,
    price: "25,550"
  },
  {
    id: 2,
    make: "Tesla",
    model: "Model 3",
    image: "./assets/carimages/Tesla.png",
    useablecapkWH: 75.0,
    rangemiles: 285,
    acceleration: 4.6,
    topspeedmph: 145,
    torque: 443,
    body: "Saloon",
    fastchargemins: 22,
    standardcharge: 465,
    price: "51,490"
  },
  {
    id: 3,
    make: "MG",
    model: "ZS",
    image: "./assets/carimages/MG.png",
    useablecapkWH: 44.5,
    rangemiles: 140,
    acceleration: 8.2,
    topspeedmph: 87,
    torque: 260,
    body: "SUV",
    fastchargemins: 36,
    standardcharge: 480,
    price: "22,495"
  },
  {
    id: 4,
    make: "Kia",
    model: "e-Niro",
    image: "./assets/carimages/Kia.png",
    useablecapkWH: 67.1,
    rangemiles: 235,
    acceleration: 7.8,
    topspeedmph: 104,
    torque: 291,
    body: "SUV",
    fastchargemins: 44,
    standardcharge: 630,
    price: "34,995"
  },
  {
    id: 5,
    make: "Audi",
    model: "e-tron 50",
    image: "./assets/carimages/Audi.png",
    useablecapkWH: 71.0,
    rangemiles: 175,
    acceleration: 6.8,
    topspeedmph: 118,
    torque: 398,
    body: "SUV",
    fastchargemins: 26,
    standardcharge: 420,
    price: "59,900"
  },
  {
    id: 6,
    make: "Nissan",
    model: "Leaf",
    image: "./assets/carimages/Nissan.png",
    useablecapkWH: 40.0,
    rangemiles: 135,
    acceleration: 7.9,
    topspeedmph: 89,
    torque: 236,
    body: "Hatchback",
    fastchargemins: 40,
    standardcharge: 390,
    price: "26,845"
  },
  {
    id: 7,
    make: "Volkswagen",
    model: "e-Golf",
    image: "./assets/carimages/Volkswagen.png",
    useablecapkWH: 35.8,
    rangemiles: 120,
    acceleration: 9.6,
    topspeedmph: 93,
    torque: 214,
    body: "Hatchback",
    fastchargemins: 36,
    standardcharge: 315,
    price: "28,075"
  },
  {
    id: 8,
    make: "Hyundai",
    model: "Kona",
    image: "./assets/carimages/Hyundai.png",
    useablecapkWH: 67.1,
    rangemiles: 250,
    acceleration: 7.9,
    topspeedmph: 104,
    torque: 291,
    body: "SUV",
    fastchargemins: 44,
    standardcharge: 420,
    price: "35,600"
  },
  {
    id: 9,
    make: "Mini",
    model: "Electric",
    image: "./assets/carimages/Mini.png",
    useablecapkWH: 32.6,
    rangemiles: 115,
    acceleration: 7.3,
    topspeedmph: 93,
    torque: 199,
    body: "Hatchback",
    fastchargemins: 28,
    standardcharge: 195,
    price: "24,900"
  },
  {
    id: 10,
    make: "Jaguar",
    model: "I-Pace",
    image: "./assets/carimages/Jaguar.png",
    useablecapkWH: 90.0,
    rangemiles: 230,
    acceleration: 4.8,
    topspeedmph: 124,
    torque: 513,
    body: "SUV",
    fastchargemins: 44,
    standardcharge: 810,
    price: "64,495"
  }
];

export default carlist;
